@startuml
participant "laby: Labyrinthe" as Laby
participant "cp: CasePiege" as CasePiege
participant "e: Entite" as Entite

-> Laby : deplacerPerso()
activate Laby

Laby -> CasePiege : onStepOn(e: Entite)
activate CasePiege

CasePiege -> Entite : prendreDegat(d: double)

CasePiege --> Laby : 
deactivate CasePiege
@enduml