@startuml
class Player {
  - maxHp: int
  + Player(x: int, y: int, hp: int)
  + Player(x: int, y: int)
  + getMaxHp(): int
}

class Entite {
  - enVie: boolean
  - hp: int
  + Entite(x: int, y: int)
  + Entite(x: int, y: int, hp: int)
  + prendreDegat(degats: int): void
  + getHp(): int
}

Player --|> Entite

hide Entite::y
hide Entite::x
hide Entite::setX
hide Entite::getX
hide Entite::setY
hide Entite::getY
hide Entite::etrePresent
@enduml