@startuml
participant "di: DeplacementIntelligent" as DI
participant "labyrinthe: Labyrinthe" as Laby
participant "joueur: Player" as Player
participant "monstre: Monstre" as Monstre

-> DI : deplacement(labyrinthe, monstre)
activate DI

DI -> Laby : getPlayer()
Laby --> DI : Player

alt [joueur == null]
    DI --> : return
else [joueur != null]
    
    note over DI : Récupère positions\nmonstre et joueur
    DI -> Monstre : getX(), getY()
    Monstre --> DI : positions
    
    DI -> Player : getX(), getY()
    Player --> DI : positions
    
    note over DI : Calcule distance initiale
    DI -> DI : calculerDistance()
    
    note over DI : Test les 4 directions
    loop [4 directions]
        DI -> Laby : canEntityMoveTo(nouveauY, nouveauX)
        Laby --> DI : boolean
        
        opt [mouvement possible]
            DI -> DI : calculerDistance()
        end
    end
    
    opt [. déplace vers la meilleure position trouvée]
        DI -> Monstre : setPosition(meilleurY, meilleurX)
    end
end

deactivate DI
@enduml