@startuml

title Diagramme de séquence pour l'affichage d'une case escalier

participant "zd: ZeldiabloDessin" as ZD
participant "laby: Labyrinthe" as Laby
participant "case: Case" as Case
participant "gc: GraphicsContext" as GC

-> ZD : dessinerJeu(jeu: Jeu, canvas: Canvas)
activate ZD

ZD -> ZD : labyUI(laby: Labyrinthe, gc: GraphicsContext, canvas: Canvas)
activate ZD

loop [pour chaque position x, y]
    ZD -> Laby : getCase(y: int, x: int)
    activate Laby
    Laby --> ZD : Case
    deactivate Laby
    
    
    ZD -> GC : setFill(Color.BLUE)
    activate GC
    deactivate GC
    
        
    ZD -> GC : gc.fillRect(0,0,c.getWidth(),c.getHeight())
    activate GC
    deactivate GC
end

deactivate ZD
@enduml