@startuml
participant Entite
participant "CaseEscalier" as CaseEscalier
participant "ZeldiabloJeu" as Jeu
participant "Labyrinthe" as Laby
participant "Player" as Joueur

Entite -> CaseEscalier : onAction(entite, jeu)
CaseEscalier -> Jeu : getLaby()
Jeu -> Laby : getNomFichier()
alt Escalier descendant et nomFichier se termine par "labyjeu1.txt"
    CaseEscalier -> Jeu : getLaby()
    Jeu -> Laby : getPlayer()
    Laby -> Joueur : possedeItem("Amulette")
    alt Joueur possède l'amulette
        Joueur -> Joueur : setaGagne(true)
        return
    else
        Entite -> Entite : setMsgToSay("Il me manque quelque chose...")
        return
    end
else
    CaseEscalier -> Jeu : changeLevel(monte)
end
@enduml