@startuml
participant Entite
participant "c1: CaseEscalier" as CaseEscalier
participant "ZJ: ZeldiabloJeu" as Jeu
participant "L1: Labyrinthe" as Laby
participant "P1: Player" as Joueur

Entite -> CaseEscalier : onAction(entite, jeu)
CaseEscalier -> Jeu : getLaby()
Jeu -> Laby : getNomFichier()
alt Escalier descendant et nomFichier se termine par "labyjeu1.txt"
    CaseEscalier -> Jeu : getLaby()
    Jeu -> Laby : getPlayer()
    Laby -> Joueur : possedeItem("Amulette")
    Laby <- Joueur: true
    alt Joueur possède l'amulette
        Joueur -> Joueur : setaGagne(true)
        return
    else
        Entite -> Entite : setMsgToSay("Il me manque quelque chose...")
        return
    end
else
    CaseEscalier -> Jeu : changeLevel(monte)
end
@enduml