@startuml

title Diagramme de séquence pour le chargement des niveaux

participant "ZJ: ZeldiabloJeu" as Jeu
participant "File" as FileSystem
participant "Arrays" as ArraysUtil
participant "L: Labyrinthe" as Laby

-> Jeu : chargementNiveau()
activate Jeu

Jeu -> FileSystem : new File("labyJeu").listFiles()
activate FileSystem
FileSystem --> Jeu : folder
deactivate FileSystem

note over Jeu : Trie les niveaux par odre alphabétique

Jeu -> ArraysUtil : sort(fichiers)


note over Jeu : Création des labyrinthes pour chaque fichier

Jeu -> Laby : new Labyrinthe(f, this)
activate Laby
note right : Pour chaque fichier trié
Laby --> Jeu : labyrinthe
deactivate Laby

note over Jeu : niveaux.add(labyrinthe)

deactivate Jeu

@enduml
