@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

interface Action << interface >> {
  + onStepOn(Entite): void
  + onAction(Entite, ZeldiabloJeu): void
}
class Case {
  + addItem(Item): void
  + getItem(): Item
  + getCaseType(): CaseType
  + onStepOn(Entite): void
  + onAction(Entite, ZeldiabloJeu): void
  + hasItem(): boolean
  + removeItem(): void
  + getIsWalkable(): boolean
  + toString(): String
  + setIsWalkable(boolean): void
}
class CaseEscalier {
  + onAction(Entite, ZeldiabloJeu): void
}
class CaseMur
class CaseOuverture {
  + onStepOn(Entite): void
}
class CasePancarte {
  + onStepOn(Entite): void
}
class CasePiege {
  + onStepOn(Entite): void
  + getDegats(): double
}
class CasePorte {
  + ouvrir(): void
}
enum CaseType << enumeration >> {
  + valueOf(String): CaseType
  + values(): CaseType[]
}
class CaseVide {
  + hasItem(): boolean
  + removeItem(): void
  + addItem(Item): void
  + getItem(): Item
}

Case           -[#008200,dashed]-^  Action
Case          "1" *-[#595959,plain]-> "caseType\n1" CaseType
CaseEscalier   -[#000082,plain]-^  Case
CaseMur        -[#000082,plain]-^  Case
CaseOuverture  -[#000082,plain]-^  Case
CasePancarte   -[#000082,plain]-^  Case
CasePiege      -[#000082,plain]-^  Case
CasePorte      -[#000082,plain]-^  Case
CaseVide       -[#000082,plain]-^  Case
@enduml
