@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class Entite {
  + getX(): int
  + getMaxHp(): double
  + setMsgToSay(String): void
  + setPosition(int, int): void
  + setEnVie(boolean): void
  + prendreDegat(double): void
  + getHp(): double
  + gagnerVie(double): boolean
  + mettreDegat(Entite): void
  + setEtatVisuelle(EtatVisuelle): void
  + setHp(double): void
  + getMsgToSay(): String
  + setX(int): void
  + estMort(): boolean
  + setY(int): void
  + getY(): int
  + aCote(Entite): boolean
  + getDegat(): double
}
class EtatVisuelle {
  + getNom(): String
}
enum Intelligence << enumeration >> {
  + values(): Intelligence[]
  + valueOf(String): Intelligence
}
class Monstre {
  - setIntelligence(Intelligence): void
  + getDeplacementStrategie(): DeplacementStrategie
  + deplacer(Labyrinthe): void
  + setDeplacementStrategie(DeplacementStrategie): void
}
class MonstreStatique
class Player {
  + setSpriteJoueur(int): void
  + getInventory(): ArrayList<Item>
  + setEnVie(boolean): void
  + aGagne(): boolean
  + setaGagne(boolean): void
  + getSpriteJoueur(): int
  + clone(): Player
  + getVie(): double
  + mettreDegat(Entite): void
  + setInventory(ArrayList<Item>): void
}

Entite          "1" *-[#595959,plain]-> "etatVisuelle\n1" EtatVisuelle
Monstre          -[#000082,plain]-^  Entite
Monstre          -->                 Intelligence
MonstreStatique  -[#000082,plain]-^  Monstre
Player           -[#000082,plain]-^  Entite
@enduml
