@startuml
Activate MainZeldiablo
MainZeldiablo -> ZeldiabloJeu: Update(secondes ,clavier)
Activate ZeldiabloJeu
ZeldiabloJeu -> ZeldiabloJeu: DeplacerPersonnage(Clavier)
ZeldiabloJeu -> VariablesGlobales: getters()
Activate VariablesGlobales
VariablesGlobales --> ZeldiabloJeu
Deactivate VariablesGlobales
ZeldiabloJeu -> ZeldiabloJeu: inputInv(Clavier)
ZeldiabloJeu --> MainZeldiablo
Deactivate ZeldiabloJeu
Deactivate MainZeldiablo
@enduml