@startuml
title "Diagramme affichage Start"
participant "jeu:ZeldiabloDessin" as jeu
participant "v:VariableGlobales" as v
-> jeu: dessinerJeu(Jeu jeu, Canvas canva
Activate jeu
alt if player mort
     jeu -> jeu: startUI
     activate jeu
     jeu <-- jeu
     deactivate jeu

     jeu -> v : Chargement du curseur start
     Activate v
     v --> jeu
     Deactivate v
else
       jeu -> jeu: labyUI()
       activate jeu
       jeu <-- jeu
       deactivate jeu

       jeu -> jeu: HeroUI()
        activate jeu
        jeu <-- jeu
        deactivate jeu

     alt menuOuvert True
       jeu -> jeu: invIU()
       activate jeu
        jeu <-- jeu
        deactivate jeu
     end
end
<--jeu
Deactivate jeu
@enduml