@startuml
title Diagramme de séquence pour la récupération de texte IA lors de la récupération d'un item

participant "l: Labyrinthe" as Lab
participant "p: Player" as P
participant "c: Case" as C
participant "Pr: Prompt" as Pr
participant "rayanestaszewski.fr/gpt" as API

 -> Lab : ramasserItem(joueur)
Lab -> Lab : getCase(y, x)
Lab -> C : hasItem()

alt la case contient un item
    Lab -> C : getItem()

    |||
    
    Lab -> Pr : askGptForMsgWhenPickingItem(nomItem, callback)
    activate Pr
    
    Pr -> Pr : construire prompt
    Pr -> API : makeHttpRequest(prompt, callback)
    activate API
    
    API --> Pr : réponse texte
    deactivate API
    
    Pr -> P : setMsgToSay(texteIA)
    deactivate Pr
    end
@enduml