@startuml

!theme plain
top to bottom direction
skinparam linetype polyline

class Case {
   item: Item
   couleur: Color
   isWalkable: boolean
}
class Entite {
   etatVisuelle: EtatVisuelle
   hp: double
   maxHp: double
   x: int
   degat: double
   y: int
   enVie: boolean
}
class Item {
   name: String
}
class Sprite {
   img: Image
}
class ZeldiabloDessin

Case             --^  Sprite
Entite           --^  Sprite
Item             --^  Sprite
Sprite           <...  ZeldiabloDessin
@enduml


@enduml