@startuml

!theme plain
top to bottom direction
skinparam linetype ortho


package CaseSub{
    class Case
    class CaseEscalier
    class CaseMur
    class CaseOuverture
    class CasePancarte
    class CasePiege
    class CasePorte
    class CaseVide
}

enum Direction << enumeration >>

package Deplacement {
    class DeplacementFuyard
    class DeplacementHasard
    class DeplacementIntelligent
    class DeplacementRapprochement
    class DeplacementStatique
    interface DeplacementStrategie << interface >>
    class node37 as "package  gameZeldiablo.Zeldiablo.StrategieDeplacement.BellmandFord" << package >>
    enum Intelligence << enumeration >>
}


package EntiteSub{
class Entite
    class Monstre
    class MonstreStatique
    class Player
}

package ItemSub{
    class Item
    class Epee
    class Food
    class Hache
    class ItemDefault
    class Amulette
    class Baton
}

class Labyrinthe
class MainZeldiablo
class Prompt
class Sprite
enum TypeItem << enumeration >>
class VariablesGlobales
class ZeldiabloDessin
class ZeldiabloJeu


Amulette                  -[#000082,plain]-^  Item
Baton                     -[#000082,plain]-^  Item
Case                      -[#000082,plain]-^  Sprite
CaseEscalier              -[#000082,plain]-^  Case
CaseMur                   -[#000082,plain]-^  Case
CaseOuverture             -[#000082,plain]-^  Case
CasePancarte              -[#000082,plain]-^  Case
CasePiege                 -[#000082,plain]-^  Case
CasePorte                 -[#000082,plain]-^  Case
CaseVide                  -[#000082,plain]-^  Case
CaseVide                 "1" *-[#595959,plain]-> "item\n1" Item
DeplacementFuyard         -[#008200,dashed]-^  DeplacementStrategie
DeplacementHasard         -[#008200,dashed]-^  DeplacementStrategie
DeplacementIntelligent    -[#008200,dashed]-^  DeplacementStrategie
DeplacementRapprochement  -[#008200,dashed]-^  DeplacementStrategie
DeplacementStatique       -[#008200,dashed]-^  DeplacementStrategie
Entite                    -[#000082,plain]-^  Sprite
Epee                      -[#000082,plain]-^  Item
Food                      -[#000082,plain]-^  Item
Hache                     -[#000082,plain]-^  Item
Item                      -[#000082,plain]-^  Sprite
ItemDefault               -[#000082,plain]-^  Item
Labyrinthe                ->  Amulette
Labyrinthe               "1" *-> "gameBoard\n*" Case
Labyrinthe               "1" *-[#595959,plain]-> "monstres\n*" Monstre
Labyrinthe               "1" *-[#595959,plain]-> "joueur\n1" Player
MainZeldiablo             ->  ZeldiabloDessin
MainZeldiablo             ->  ZeldiabloJeu
Monstre                  "1" *-[#595959,plain]-> "deplacementStrategie\n1" DeplacementStrategie
Monstre                   -[#000082,plain]-^  Entite
MonstreStatique           -[#000082,plain]-^  Monstre
Player                    -[#000082,plain]-^  Entite
Player                   "1" *-[#595959,plain]-> "inventory\n*" Item
Sprite                    -[#000082,plain]-^  ZeldiabloDessin
ZeldiabloJeu              ->  Labyrinthe
@enduml
