@startuml

title Diagramme de classe de case escalier

interface Action {
  + onStepOn(Entite)
}

abstract Case {
  - x : int
  - y : int
  - couleur : Color
  - isWalkable : boolean
  + ChangeLevel()
  + onStepOn(Entite)
}

class CaseEscalier {
  - jeu : ZeldiabloJeu
  + ChangeLevel()
  + onStepOn(Entite)
}

class ZeldiabloJeu {
  - niveaux : ArrayList<Labyrinthe>
  - currentLevel : int
  - estFini : boolean
  - currentlyMoving : boolean
  + nextLevel()
  + getLaby() : Labyrinthe
  + chargementNiveau()
}

class Labyrinthe {
  - gameBoard : Case[][]
  - joueur : Player
  - monstres : ArrayList<Monstre>
  + getPlayer() : Player
}

abstract Entite {
  - x : int
  - y : int
  - hp : double
  - maxHp : double
  - enVie : boolean
  + setEnVie(boolean)
  + setHp(double)
  + getHp() : double
}

class Player {
  - inventory : ArrayList<Item>
  + setEnVie(boolean)
  + setInventory(ArrayList<Item>)
  + setHp(double)
  + getInventory() : ArrayList<Item>
}

ZeldiabloJeu --> "*" Case : gameBoard
Labyrinthe --> Player : joueur
CaseEscalier --|> Case
Case ..|> Action
Player --|> Entite

@enduml