@startuml

title Sequence d'attaque du joueur

actor Joueur
participant "zeldiabloJeu:ZeldiabloJeu" as Jeu
participant "labyrinthe:Labyrinthe" as Laby
participant "joueur:Player" as Player
participant "monstre:Monstre" as Monstre

Joueur -> Jeu: press X
activate Jeu
Jeu -> Laby: attaqueJoueur()
activate Laby

Laby -> Player: setEtatVisuelle(ATTAQUE_JOUEUR)
activate Player

loop pour chaque monstre
  Laby -> Player: aCote(monstre)

  alt monstre à côté
    Laby -> Player: mettreDegat(monstre)
    Player -> Monstre: prendreDegat(degat)
    activate Monstre

    alt monstre mort
      Monstre -> Monstre: setEtatVisuelle(MORT)
      Laby -> Laby: monstres.remove(monstre)
      Player -> Player: heal(1 HP)
    end
    deactivate Monstre
  end
end

deactivate Player
deactivate Laby
deactivate Jeu

@enduml