@startuml
'https://plantuml.com/sequence-diagram

participant "l:Labyrinthe" as l
participant "f:food" as f
participant "p:Player" as p

Activate l
->l:KeypressedX
l->f:Use()
Activate f
f->p: GagnerVie(VaribleGlobale.HEAL_FOOD)
Activate p
f<--p
Deactivate p
l<--f
Deactivate f
<--l
@enduml